#upload attachments
librinfo_media.upload:
    path:     librinfo/media/upload
    defaults: { _controller: LibrinfoMediaBundle:Upload:upload }
# remove uploaded attachments
librinfo_media.remove:
    path:     librinfo/media/remove/{fileName}/{fileSize}/{tempId}
    defaults: { _controller: LibrinfoMediaBundle:Upload:remove }
    
# load uploaded files
librinfo_media.load:
    path:     librinfo/media/load/{ownerId}/{ownerType}
    defaults: { _controller: LibrinfoMediaBundle:Upload:load } 

