services:
    
### FORM TYPES ###
    librinfo_media.form.type.dropzone:
        class: Librinfo\MediaBundle\Form\Type\DropzoneType
        tags:
            - { name: form.type, alias: librinfo_dropzone }